# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71e0026f65bd5a7937b4ac3446300fd2384deafc05462bb1cf927c28ad8d015d4390473a71175a15bb6c25c131fb83450631c8aa32f12c6ee5a61ad456cdc4b9

test:
  secret_key_base: 7b6344afc3fc59b990284f63d0b6428c1970704963ac062f0496f86a9612215e985eafcb825b1c52e4a6fbbb168a74aa6fb75a61973b41adf7ca30e0407c9c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
